name: 🦑 Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # 每天 0 点 UTC 运行
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: yangguohao
          config_timezone: Asia/Shanghai
          # 欢迎按 Metrics 文档添加更多插件，比如:
          # plugin_calendar: yes
          # plugin_languages: yes
